# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: check-yaml
        exclude: ^(docs/|scripts/|\.gitlab/|\.pytest_cache/|\.cache/|xxx\.py|cert/.*)$
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: ^(docs/|scripts/|\.gitlab/|\.pytest_cache/|\.cache/|xxx\.py|cert/.*)$
      - id: check-added-large-files
      - id: check-json
        exclude: ^(docs/|scripts/|\.gitlab/|\.pytest_cache/|\.cache/|xxx\.py|cert/.*)$
      - id: check-merge-conflict

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0  # Latest stable version of Flake8
    hooks:
      - id: flake8
        args:
          - '--max-line-length=200'
          - '--ignore=E128,E126,E121,E123'
        additional_dependencies: []
        exclude: ^(docs/|scripts/|\.gitlab/|\.pytest_cache/|\.cache/|xxx\.py|cert/.*|alembic/versions/.*)$

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0  # Use the latest stable version
    hooks:
      - id: isort
        exclude: ^(docs/|scripts/|\.gitlab/|\.pytest_cache/|\.cache/|xxx\.py|cert/.*)$
