# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ticketai-chat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stonesearch.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e3d81d6f62074954b64192b4ef0e9122 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9dfb41fe0b4f42a0ad89689e07a4899f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stonesearch.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3d81d6f62074954b64192b4ef0e9122 }}/ticketai-chat:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ticketai-chat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_232d46d359034374ab5360579fbdc527 }}
        images: 'stonesearch.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e3d81d6f62074954b64192b4ef0e9122 }}/ticketai-chat:${{ github.sha }}'